[APISMART-615] add new mutation to update personendaten of antragsteller
europace/kex-vorgang-update-api pull request #17
Opened 2021-08-10 09:52 UTC by sgrell

2021-08-10 21:44 UTC, cryptoki requested changes
Personendaten bitte korrigieren. 🐇

2021-08-10 21:44 UTC, cryptoki commented on README.md
> +### Personendaten
hier bist Du verrutscht. Das gehört zum Abschnitt Wohnsituation. Nimmst Du das direkt vom Import? Ich habe festgestellt, dass die Daten im Import nicht immer vollständig sind. Hier würde ich immer noch mal abgleichen.

2021-08-12 07:22 UTC, sgrell commented on README.md
> +### Personendaten
ups, ist korrigiert. Ich habe das aus dem GraphQL-Schema genommen und mit dem Import abgeglichen.

2021-08-12 07:31 UTC, cryptoki approved these changes

2021-08-12 08:26 UTC, huehnerlady approved these changes
🐓

2021-08-12 09:30 UTC, merged