Api 2 en
europace/kex-vorgang-update-api pull request #36
Opened 2021-12-15 12:59 UTC by huehnerlady

2021-12-15 13:01 UTC, huehnerlady commented on README.md
>  > Die alten Update-Endpunkte sind [hier](#legacy-update-apis) dokumentiert.
wird vorher durch #35 gelöscht

2021-12-15 13:58 UTC, HungryHarry requested changes
Wie beschrieben war ich mir beim "aktiv" nicht sicher, obs nur durchgerutscht oder beabsichtigt ist ("archived" ist auch englisch) - ansonsten passts, bis auf 2 kleine Typos. MEGAAA

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +* The Vorgang has to be aktiv, which means it must not be archived.
```suggestion
* The Vorgang has to be active, which means it must not be archived.
```

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +* The Vorgang has to be aktiv, which means it must not be archived.
Oder ist das hier ein "technical term"

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +* The `antragstellerId` has correspond to an Antragsteller in the Vorgang.
```suggestion
* The `antragstellerId` refers to an existing Antragsteller within the Vorgang.
```

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +* The `antragstellerId` has correspond to an Antragsteller in the Vorgang.
Nur ein Vorschlag - es geht auch deine Variante ;) 
Edit: Müsste dann wahrscheinlich bei allen Blöcken angepasst werden, von daher kann es gern ignoriert werden. :)

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +* The [Beschaeftigung](#beschaeftigung) is only taking one Beschäftigungsart into acocunt and uses only the corresponding fields for the update.
```suggestion
* The [Beschaeftigung](#beschaeftigung) is only taking one Beschäftigungsart into account and uses only the corresponding fields for the update.
```

2021-12-15 13:58 UTC, HungryHarry commented on README.md
> +> If we do server-side adapions of the data to ensure a valid dataset, we add hints to the `messages` field of the response. These are purely to inform the client, there are NEVER any errors in the `
```suggestion
> If we do server-side adaptions of the data to ensure a valid dataset, we add hints to the `messages` field of the response. These are purely to inform the client, there are NEVER any errors in the `messages` field. Errors will be only shown in the `errors` field of the response.
```

2021-12-16 07:30 UTC, huehnerlady commented on README.md
> +* The `antragstellerId` has correspond to an Antragsteller in the Vorgang.
```suggestion
* The `antragstellerId` has torefer to an existing Antragsteller in the Vorgang.
```

2021-12-16 07:33 UTC, huehnerlady commented on README.md
> +* The Vorgang has to be aktiv, which means it must not be archived.
ich habe das jetzt nochmal neu verfasst, wollte das schon als technical term drin haben, war aber unverständlich. ist es so besser?

2021-12-16 07:37 UTC, HungryHarry commented on README.md
> +* The Vorgang has to be aktiv, which means it must not be archived.
Passt - find ich gut so :)

2021-12-16 07:38 UTC, HungryHarry approved these changes
🇬🇧

2021-12-16 07:38 UTC, merged